# Use root/example as user/password credentials
version: '3.1'

services:

  backend:
    build: .
    image: opendata-server:latest
    restart: always
    ports:
      - "8083:8080"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: __MY_SECRET_PASSWORD__
      MONGO_INITDB_DATABASE: opendata
      MONGO_SERVER: mongo

  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
      - ./data/dump:/dump
      - ./data/opendata:/opendata:ro
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: __MY_SECRET_PASSWORD__
      MONGO_INITDB_DATABASE: opendata

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: __MY_SECRET_PASSWORD__
